#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

######################################################################
#
#       TIPS!
#
# init repository first time for this machine
# restic --repo sftp:vlad@solaris.domus:/mnt/bank/backups/rbackups/$(hostname) init
#
# list available snapshots for this machine
# restic --repo sftp:vlad@solaris.domus:/mnt/bank/backups/rbackups/$(hostname) snapshots
#
# mount remote repository to browse files
# mkdir /tmp/backup && restic --repo sftp:vlad@solaris.domus:/mnt/bank/backups/rbackups/$(hostname) mount /tmp/backup
#

YELLOW='\033[33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [[ -z "${RESTIC_PASSWORD}" ]]; then
    printf "\n\t${RED}RESTIC_PASSWORD env var is not set!${NC}\n\n"
    exit 1
fi

REPOSITORY=sftp:vlad@solaris.domus:/mnt/bank/backups/rbackups/$(hostname)

printf "\n\t${YELLOW}Backing up home to '${REPOSITORY}'..${NC}\n\n"

restic                                                     \
    --cleanup-cache                                        \
    --repo $REPOSITORY                                     \
    --one-file-system                                      \
    --exclude-caches                                       \
    --exclude "$HOME/.?*"                                  \
    --exclude "$HOME/Projects/__containers"                \
    backup     $HOME                                       \
&&                                                         \
printf "${YELLOW}Checking..${NC}\n"                        \
&&                                                         \
restic                                                     \
    --repo $REPOSITORY                                     \
    check                                                  \
&&                                                         \
printf "${YELLOW}Purgin old shapshots..${NC}\n"            \
&&                                                         \
restic                                                     \
    --repo $REPOSITORY                                     \
    --keep-last 4                                          \
    --keep-daily 7                                         \
    --keep-weekly 5                                        \
    --keep-monthly 12                                      \
    --keep-yearly 3                                        \
    --prune                                                \
    forget                                                 \
&&                                                         \
printf "${YELLOW}Repository stats..${NC}\n"                \
&&                                                         \
restic                                                     \
    --repo $REPOSITORY                                     \
    stats                                                  \
&&                                                         \
cowsay -f moose -b ' Backup complete! ' | lolcat
