# if env variable EDITOR is set to vi/vim then ZSH uses vi/vim key bindings,
# i.e. classical ctrl+a to get to the start of the line will not work.
# following command switches key bindings to default.

bindkey -e

ZSH=$HOME/.oh-my-zsh

ZSH_THEME="afowler"

plugins=(
	archlinux sudo 
	rsync tmux docker	
	git 
	lein mvn 
	)

# source common aliases
source $HOME/.aliases

# source environment specific aliases
[ -f $HOME/.environment.aliases ] && source $HOME/.environment.aliases

# add extra executable
export PATH=$HOME/.bin:$PATH

# start oh-my-zsh routine
source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8
