# if env variable EDITOR is set to vi/vim then ZSH uses vi/vim key bindings,
# i.e. classical ctrl+a to get to the start of the line will not work.
# following command switches key bindings to default.

bindkey -e

ZSH=$HOME/.oh-my-zsh

ZSH_THEME="afowler"

plugins=(
	sudo 
	rsync
	fzf
	docker
	git
	lein mvn
	python virtualenv pip pyenv
	ansible
	pass
)

# add extra executable
export PATH=$HOME/.bin:$HOME/.local/bin:$PATH

# disable oh-my-zsh auto update
export DISABLE_AUTO_UPDATE="true"
#export VIRTUAL_ENV_DISABLE_PROMPT=

# start oh-my-zsh routine
source $ZSH/oh-my-zsh.sh

# source common aliases
source $HOME/.aliases

# source environment specific aliases
[ -f $HOME/.environment.aliases ] && source $HOME/.environment.aliases

export SAVEHIST=100000000
export HISTSIZE=10000

export LANG=en_US.UTF-8
export EDITOR=vim
